//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egress.Infra.CrossCutting.Resource {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodeResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodeResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Egress.Infra.CrossCutting.Resource.ErrorCodeResource", typeof(ErrorCodeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NOT_FOUND_ERROR {
            get {
                return ResourceManager.GetString("NOT_FOUND_ERROR", resourceCulture);
            }
        }
        
        public static string UNEXPECTED_ERROR_OCURRED {
            get {
                return ResourceManager.GetString("UNEXPECTED_ERROR_OCURRED", resourceCulture);
            }
        }
        
        public static string AMOUNT_IS_GREATER_THEN_TOTAL {
            get {
                return ResourceManager.GetString("AMOUNT_IS_GREATER_THEN_TOTAL", resourceCulture);
            }
        }
        
        public static string HAS_ALREADY_BEEN_ACCEPTED {
            get {
                return ResourceManager.GetString("HAS_ALREADY_BEEN_ACCEPTED", resourceCulture);
            }
        }

        public static string ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ALREADY_EXISTS", resourceCulture);
            }
        }
    }
}
